export const SKILL_NAMES = [
  'analyze-project',
  'explore-metric',
  'instrument-events',
  'onboard-confidence',
  'onboard-confidence-dry-run',
  'setup-session-recording',
  'setup-warehouse',
  'setup-warehouse-bigquery',
  'setup-warehouse-databricks',
  'setup-warehouse-redshift',
  'setup-warehouse-snowflake',
  'migrate-eppo',
  'migrate-optimizely',
  'migrate-posthog',
  'migrate-statsig',
] as const;
